version: "3"
services:
  django:
    container_name: django_backend
    build: ./backend
    tty:  true
    volumes:
      - ./backend:/backend
    ports:
      - 3030:3030
#    depends_on:
#      - postgres
  
  react:
    container_name: react_frontend
    build: ./frontend
    tty:  true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000


#  postgres:
#    container_name: postgres
#    image: postgres:13
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: postgres_db
#    volumes:
#      - db_data:/var/lib/posrgresql/data

#volumes:
#  db_data: {}